[build]
  command = "npm run build"
  publish = "dist/djmaximo-angular/browser"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_ANGULAR_RUNTIME = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
